### ISSUE TITLE
remove unneeded onHeartbeat actions

### ISSUE THREAD

**Issue by heggink** [febalci/DomoticzLife360#11]
I have removed the following in onHeartbeat in my local installation:

```
        api = life360(authorization_token=self.authorization_token, username=Parameters["Username"], password=Parameters["Password"])
        if api.authenticate():
            self.id = api.get_circle_id()
```

Only the following remains:
`            circle = api.get_circle(self.id)`

So far working fine. Not sure how it works over prolonged periods but let's see. Will report back later. Should make the plugin more efficient.

Herman

**Comment by febalci** [comment]
Was not sure if the circle_id was constant all the time.  Removed it in v2.0.0. Thanks...
