### ISSUE TITLE
googlemapsapi issue

### ISSUE THREAD

**Issue by heggink** [febalci/DomoticzLife360#9]
every time I cross the atlantic, the pluggin errors out on hearbeat causing domoticz to lose memory dramatically (i.e. run out of memory within 5 days). 
Cause seems to be the following:

`URL:https://maps.googleapis.com/maps/api/directions/json?origin=45.5077115,-3.5716699&destination=52.536129,5.453455&transit_mode=driving&departure_time=now&key=XXXXX `

That triggers a zero results response (as you cannot drive across the atlantic):
```
{
   "geocoded_waypoints" : [ {}, {} ],
   "routes" : [],
   "status" : "ZERO_RESULTS"
}
```
Error sequence in Domoticz:
```
2018-07-18 03:27:28.005 Error: (Life360) 'onHeartbeat' failed 'IndexError':'list index out of range'. 
2018-07-18 03:27:28.005 Error: (Life360) ----> Line 245 in /home/pi/domoticz/plugins/life360/plugin.py, function onHeartbeat 
2018-07-18 03:27:28.005 Error: (Life360) ----> Line 185 in /home/pi/domoticz/plugins/life360/plugin.py, function onHeartbeat 
2018-07-18 03:27:28.005 Error: (Life360) ----> Line 49 in /home/pi/domoticz/plugins/life360/googlemapsapi.py, function getdistance 
2018-07-18 03:27:28.005 Error: (Life360) ----> Line 33 in /home/pi/domoticz/plugins/life360/googlemapsapi.py, function make_request 
```

Call sequence as follows:
```

 plugin.py
245: _plugin.onHeartbeat()
185: currentmin = a.getdistance(self.googleapikey,self.circleLatitude,self.circleLongitude,self.myHomelat,self.myHomelon)

googlemapsapi.py:
49: req = self.make_request(type=1,url=url)
33: jsonr = jsonj["routes"][0]["legs"][0]["duration_in_traffic"]["value"]
```
Please note that I made some changes to the plugin in order to support a distance device (distance from home). My line numbers may be different compared to GitHub's

Any thoughts on how to handle this without erroring out? My python skills are absent. Also, any idea why this leads to a massive memory leak?

btw, disabling the googlemapsapi (taking the key out) fixes it.

Herman

**Comment by febalci** [comment]
It is due to the new pricing scheme of google Maps API. It is not free anymore, that's why there's a memory leak; API returns "Over_Query_Limit". Have to change Google maps API to something else; either a free service or from life360 if i can. Have to check it out when i find some free time. Thanks for the warning heggink...

**Comment by heggink** [comment]
Maybe that's a cause but what if there is no route like in my case? That also seems to be an issue. That and the fact that the plugin loses memory on the lack of error handling. This issue only came up twice and in both cases I took a flight to the US... No issues before...

**Comment by febalci** [comment]
Btw you beter delete your google maps api key in the first message!!!

**Comment by febalci** [comment]
In v2.0.0, Added if status='ZERO_RESULTS', show distance as 0 to prevent memory issues.
